---
phl:
  sortBy: '2018'
  totalField: 'total'
  nestKeys:
  - 'fund'
  - 'department'
  - 'class'
  inputFiles:
  - fiscal_year: '2017'
    path: "../data/phl/FY17-adopted.csv"
  - fiscal_year: '2018'
    path: "../data/phl/FY18-adopted.csv"
lky:
  sortBy: '2017'
  totalField: 'CheckAmt'
  nestKeys:
  - 'Funding_Source'
  - 'Agency_Name'
  - 'Sub_Agency_Name'
  - 'DepartmentName'
  inputFiles:
  - fiscal_year: '2017'
    path: "../data/lky/Expenditures_FiscalYear2017.csv"
  - fiscal_year: '2016'
    path: "../data/lky/Expenditures_FiscalYear2016.csv"
