---
phl:
  sortBy: 2019
  nestKeys:
  - 'fund'
  - 'department'
  - 'class'
  inputFiles:
  - fiscal_year: 2017
    path: "../proposed-ordinance/output/FY2017-proposed.csv"
  - fiscal_year: 2019
    path: "../proposed-ordinance/output/FY19-proposed.csv"
lky:
  sortBy: 2019
  nestKeys:
  - 'fund'
  - 'department'
  - 'class'
  input_files:
  - fiscal_year: 2017
    path: "../proposed-ordinance/output/FY2017-proposed.csv"
  - fiscal_year: 2019
    path: "../proposed-ordinance/output/FY19-proposed.csv"
